services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    volumes:
      - "./migration.sql:/docker-entrypoint-initdb.d/init.sql"
    ports:
      - "3306:3306"
  # http:
  #   build:
  #     dockerfile: Dockerfile
  #     context: .
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - db
  #   network_mode: "host"