// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/user/profile": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Get a profile",
                "responses": {
                    "201": {
                        "description": "status\": 201, \"message\": \"Created\", \"data\": string}",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "400": {
                        "description": "status\": 400, \"message\": \"Bad Request\", \"data\": null}",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "409": {
                        "description": "status\": 409, \"message\": \"Conflict\", \"data\": null}",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "500": {
                        "description": "status\": 500, \"message\": \"Internal Server Error\", \"data\": null}",
                        "schema": {
                            "type": "json"
                        }
                    }
                }
            }
        },
        "/user/search": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Search users from query",
                "responses": {
                    "201": {
                        "description": "status\": 201, \"message\": \"Created\", \"data\": string}",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "400": {
                        "description": "status\": 400, \"message\": \"Bad Request\", \"data\": null}",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "409": {
                        "description": "status\": 409, \"message\": \"Conflict\", \"data\": null}",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "500": {
                        "description": "status\": 500, \"message\": \"Internal Server Error\", \"data\": null}",
                        "schema": {
                            "type": "json"
                        }
                    }
                }
            }
        },
        "/user/signin": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Sign in to the account",
                "responses": {
                    "200": {
                        "description": "status\": 200, \"message\": \"OK\", \"data\": string}",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "400": {
                        "description": "status\": 400, \"message\": \"Bad Request\", \"data\": null}",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "401": {
                        "description": "status\": 401, \"message\": \"Unauthorized\", \"data\": null}",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "404": {
                        "description": "status\": 404, \"message\": \"Not Found\", \"data\": null}",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "500": {
                        "description": "status\": 500, \"message\": \"Internal Server Error\", \"data\": null}",
                        "schema": {
                            "type": "json"
                        }
                    }
                }
            }
        },
        "/user/signup": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Create an account",
                "responses": {
                    "201": {
                        "description": "status\": 201, \"message\": \"Created\", \"data\": string}",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "400": {
                        "description": "status\": 400, \"message\": \"Bad Request\", \"data\": null}",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "409": {
                        "description": "status\": 409, \"message\": \"Conflict\", \"data\": null}",
                        "schema": {
                            "type": "json"
                        }
                    },
                    "500": {
                        "description": "status\": 500, \"message\": \"Internal Server Error\", \"data\": null}",
                        "schema": {
                            "type": "json"
                        }
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8000",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Blog API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
